#' Summarize the \code{runMatch} annotation results
#' 
#' Summarizes the annotation data files generated by \code{runMatch}. Writes either one (single MS mode) or
#' two (coupled MS modes) tab delimited text files containing a summary of annotation hits sorted by annotation score.
#' 
#' @param project Any descriptive name for the current search run.
#' @param MSlib MS library object as generated by the \code{buildMSlibrary} function.
#' @param polarity The MS ionization mode ("negative", "positive" or "both") .
#' @param The MSlib MS library object corresponding with the other ionization mode.
#' @return NULL on a succesful completion.
#' @examples\donttest{
#' # A complete run using single ionization mode:
#' data (sampleLib)
#' runMatch ("tests/Tom_all_negative_2ch_xan.tsv","tests/rt_files_neg/","negative","tom_test",MSlib.neg)
#' summarizeMWresults ("tom_test",MSlib.neg,"negative")
#' # Summarizing after running \code{runMatch} on both ionization modes:
#' runMatch ("tests/Tom_all_negative_2ch_xan.tsv","tests/rt_files_neg/","negative","tom_test",MSlib.neg)
#' runMatch ("tests/Tom_all_negative_2ch_xan.tsv","tests/rt_files_neg/","positive","tom_test",MSlib.pos)
#' summarizeMWresults ("tom_test",MSlib.neg,"both",MSlib.pos) }
#' @export
summarizeMWresults = function(  
  project,
  MSlib,
  polarity,
  otherMSlib=NULL  
) {
  
  if (!is.null(otherMSlib)) {
    # prepare cross ref tables mass-diffs reference matrix
    xref=t(sapply(ruleset.neg$massdiff, function(x) x-ruleset.pos$massdiff))
    rownames(xref) = ruleset.neg$name
    colnames(xref) = ruleset.pos$name   
    # run the analysis twice - once for each ionization mode
    modes = list("positive","negative")
    sapply (1:2, function(i) {tests/examples/samplePool_neg.tsvtests/examples/samplePool_neg.tsv
      # set ionization modes
      this_mode = modes[[i]]
      other_mode = modes[[(i%%2+1)]]             
      print (paste("Summarizing:",this_mode))
      # choose MS library 
      if (MSlib$polarity == this_mode) { currentLib=MSlib$peaks } else { currentLib=otherMSlib$peaks }
      # read metaboMatch annotation files 
      f = list.files(pattern=paste(project,".*",this_mode,".*idList.RData",sep=""),full.names=TRUE)  
      if (length(f)!=1) { print(f); stop(paste("Need exactly one annotation file in the",mode,"ion mode")) }
      load (f)
      mainList = idList
      f = list.files(pattern=paste(project,".*",other_mode,".*idList.RData",sep=""),full.names=TRUE)
      if (length(f)!=1) { print(f); stop(paste("Need exactly one results file in the",other_mode,"ion mode")) }
      load (f)      
      refList = idList
      rm (idList)          
      sampOutput = summarizeResults(mainList,currentLib,this_mode,refList,xref)                       
      fileName = paste("mmAnnotations",project,this_mode,"tsv",sep=".")
      write.table (sampOutput,file=fileName,sep="\t",row.names=FALSE)
    }) 
  } else {             
    print (paste("Summarizing:",polarity))
    f = list.files(pattern=paste(project,".*",polarity,".*idList.RData",sep=""),full.names=TRUE)
    if (length(f)!=1) { print(f); stop(paste("Need exactly one results file in the",polarity,"ion mode")) }
    load (f)
    mainList = idList
    rm (idList)
    sampOutput = summarizeResults(mainList,MSlib$peaks,polarity) 
    fileName = paste("mmAnnotations",project,polarity,"tsv",sep=".")
    write.table (sampOutput,file=fileName,sep="\t",row.names=FALSE)      
  } 
  print ("Done")
}
